import { MainLayout } from '@/widgets/layout'
import '@/assets/style/global.scss'
import React, { Suspense } from 'react'
import { Loader } from '@/shared'

export const metadata = {
  title: 'TMED',
  // description: 'Generated by create next app',
}
export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <Suspense fallback={<Loader />}>
      <MainLayout>
        {children}
      </MainLayout>
    </Suspense>
    </body>
    </html>
  )
}
